// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `NewsInfo.jce'
// **********************************************************************

package BEC;

public final class AttitudeTypeColor implements java.io.Serializable
{
    private static AttitudeTypeColor[] __values = new AttitudeTypeColor[5];
    private int __value;
    private String __T = new String();

    public static final int _ATC_RED = 0;
    public static final AttitudeTypeColor ATC_RED = new AttitudeTypeColor(0,_ATC_RED,"ATC_RED");
    public static final int _ATC_ORANGE = 1;
    public static final AttitudeTypeColor ATC_ORANGE = new AttitudeTypeColor(1,_ATC_ORANGE,"ATC_ORANGE");
    public static final int _ATC_GRAY = 2;
    public static final AttitudeTypeColor ATC_GRAY = new AttitudeTypeColor(2,_ATC_GRAY,"ATC_GRAY");
    public static final int _ATC_LightGreen = 3;
    public static final AttitudeTypeColor ATC_LightGreen = new AttitudeTypeColor(3,_ATC_LightGreen,"ATC_LightGreen");
    public static final int _ATC_Green = 4;
    public static final AttitudeTypeColor ATC_Green = new AttitudeTypeColor(4,_ATC_Green,"ATC_Green");

    public static AttitudeTypeColor convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static AttitudeTypeColor convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private AttitudeTypeColor(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
