package BEC;

public final class E_ACCOUNT_RET
{
    public static final int E_AR_SUCC = 0;
    public static final int E_AR_USERNAME_USED = 1001;
    public static final int E_AR_PHONE_EMAIL_USED = 1002;
    public static final int E_AR_PHONE_CODE_EXPIRED = 1003;
    public static final int E_AR_PHONE_CODE_ERROR = 1004;
    public static final int E_AR_EMAIL_CODE_EXPIRED = 1005;
    public static final int E_AR_EMAIL_CODE_ERROR = 1006;
    public static final int E_AR_MACHE_CODE_EXPIRED = 1007;
    public static final int E_AR_MACHE_CODE_ERROR = 1008;
    public static final int E_AR_PHONE_NO_EXIST = 1010;
    public static final int E_AR_EMAIL_NO_EXIST = 1011;
    public static final int E_AR_FAILED_SEND_SMS = 1012;
    public static final int E_AR_PASSWORD_EMPTY = 1013;
    public static final int E_AR_PASSWORD_DIFF = 1014;
    public static final int E_AR_PASSWORD_ERROR = 1015;
    public static final int E_AR_PASSWORD_WEAK = 1016;
    public static final int E_AR_FAILED_REGISTER = 1017;
    public static final int E_AR_PHONE_FORMAT_ERROR = 1018;
    public static final int E_AR_ACCOUNT_NO_EXIST = 1019;
    public static final int E_AR_LOGIN_TYPE_ERROR = 1020;
    public static final int E_AR_PASSWORD_TOO_LONG = 1021;
    public static final int E_AR_TICKET_LENGTH_ERROR = 1022;
    public static final int E_AR_TICKET_EXPIRED = 1023;
    public static final int E_AR_TICKET_SIGN_ERROR = 1024;
    public static final int E_AR_THIRD_TOKEN_ERROR = 1025;
    public static final int E_AR_THIRD_TYPE_ERROR = 1026;
    public static final int E_AR_TICKET_ACCOUNTID_ERROR = 1027;
    public static final int E_AR_MODIFY_TYPE_NO_SUPPORT = 1028;
    public static final int E_AR_CANNOT_UNBIND = 1029;
    public static final int E_AR_THIRD_HAS_BIND = 1030;
    public static final int E_AR_MODIFY_FACE_ERROR = 1031;
    public static final int E_AR_USERNAME_LENGTH_ERROR = 1032;
    public static final int E_AR_THIRD_ACCOUNT_NO_EXIST = 1033;
    public static final int E_AR_PASSWORD_FORMAT_ERROR = 1034;
    public static final int E_AR_OPERA_TOO_FREQUENT = 1035;
    public static final int E_AR_REQUEST_PARAM_ERROR = 1036;
    public static final int E_AR_THIRD_VERFIY_ERROR = 1037;
    public static final int E_AR_USERNAME_FORMAT_ERROR = 1038;
    public static final int E_AR_VERIFY_TYPE_ERROR = 1039;
    public static final int E_AR_USERNAME_SENSTIVE = 1040;
    public static final int E_AR_INNER_MODIFY_ACCOUNT = 5000;
    public static final int E_AR_INNER_GET_ACCCOUNT_ERROR = 5001;
    public static final int E_AR_INNER_EXCEPTION = 5002;
    public static final int E_AR_INNER_GEN_TICKE_ERROR = 5003;
    public static final int E_AR_INNER_SEND_HTTP_ERROR = 5004;
    public static final int E_AR_INNER_JSON_PARSE_ERROR = 5005;
    public static final int E_AR_INNER_HTTPS_ERROR = 5006;
    public static final int E_AR_INNER_GEN_ACCCOUNTID_ERROR = 5007;
}
