// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `Beacon.jce'
// **********************************************************************

package BEC;

public final class E_FUND_INVEST_TYPE implements java.io.Serializable
{
    private static E_FUND_INVEST_TYPE[] __values = new E_FUND_INVEST_TYPE[7];
    private int __value;
    private String __T = new String();

    public static final int _E_FIT_OTHERS = 0;
    public static final E_FUND_INVEST_TYPE E_FIT_OTHERS = new E_FUND_INVEST_TYPE(0,_E_FIT_OTHERS,"E_FIT_OTHERS");
    public static final int _E_FIT_STOCK = 1;
    public static final E_FUND_INVEST_TYPE E_FIT_STOCK = new E_FUND_INVEST_TYPE(1,_E_FIT_STOCK,"E_FIT_STOCK");
    public static final int _E_FIT_BOND = 2;
    public static final E_FUND_INVEST_TYPE E_FIT_BOND = new E_FUND_INVEST_TYPE(2,_E_FIT_BOND,"E_FIT_BOND");
    public static final int _E_FIT_MIX = 3;
    public static final E_FUND_INVEST_TYPE E_FIT_MIX = new E_FUND_INVEST_TYPE(3,_E_FIT_MIX,"E_FIT_MIX");
    public static final int _E_FIT_CURRENCY = 4;
    public static final E_FUND_INVEST_TYPE E_FIT_CURRENCY = new E_FUND_INVEST_TYPE(4,_E_FIT_CURRENCY,"E_FIT_CURRENCY");
    public static final int _E_FIT_FOF = 5;
    public static final E_FUND_INVEST_TYPE E_FIT_FOF = new E_FUND_INVEST_TYPE(5,_E_FIT_FOF,"E_FIT_FOF");
    public static final int _E_FIT_INDEX = 6;
    public static final E_FUND_INVEST_TYPE E_FIT_INDEX = new E_FUND_INVEST_TYPE(6,_E_FIT_INDEX,"E_FIT_INDEX");

    public static E_FUND_INVEST_TYPE convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static E_FUND_INVEST_TYPE convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private E_FUND_INVEST_TYPE(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
