// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/home/davidwei/Beacon.jce'
// **********************************************************************

package BEC;

public final class E_PLATE_TYPE implements java.io.Serializable
{
    private static E_PLATE_TYPE[] __values = new E_PLATE_TYPE[2];
    private int __value;
    private String __T = new String();

    public static final int _E_PLATE = 1;
    public static final E_PLATE_TYPE E_PLATE = new E_PLATE_TYPE(0,_E_PLATE,"E_PLATE");
    public static final int _E_SUBJECT = 2;
    public static final E_PLATE_TYPE E_SUBJECT = new E_PLATE_TYPE(1,_E_SUBJECT,"E_SUBJECT");

    public static E_PLATE_TYPE convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static E_PLATE_TYPE convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private E_PLATE_TYPE(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
