// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `/home/davidwei/Beacon.jce'
// **********************************************************************

package BEC;

public final class E_STOCK_TYPE implements java.io.Serializable
{
    private static E_STOCK_TYPE[] __values = new E_STOCK_TYPE[7];
    private int __value;
    private String __T = new String();

    public static final int _E_DOMESTIC_A = 1;
    public static final E_STOCK_TYPE E_DOMESTIC_A = new E_STOCK_TYPE(0,_E_DOMESTIC_A,"E_DOMESTIC_A");
    public static final int _E_DOMESTIC_B = 2;
    public static final E_STOCK_TYPE E_DOMESTIC_B = new E_STOCK_TYPE(1,_E_DOMESTIC_B,"E_DOMESTIC_B");
    public static final int _E_SH_A = 3;
    public static final E_STOCK_TYPE E_SH_A = new E_STOCK_TYPE(2,_E_SH_A,"E_SH_A");
    public static final int _E_SH_B = 4;
    public static final E_STOCK_TYPE E_SH_B = new E_STOCK_TYPE(3,_E_SH_B,"E_SH_B");
    public static final int _E_SZ_A = 5;
    public static final E_STOCK_TYPE E_SZ_A = new E_STOCK_TYPE(4,_E_SZ_A,"E_SZ_A");
    public static final int _E_SZ_B = 6;
    public static final E_STOCK_TYPE E_SZ_B = new E_STOCK_TYPE(5,_E_SZ_B,"E_SZ_B");
    public static final int _E_JIJIN = 7;
    public static final E_STOCK_TYPE E_JIJIN = new E_STOCK_TYPE(6,_E_JIJIN,"E_JIJIN");

    public static E_STOCK_TYPE convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static E_STOCK_TYPE convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private E_STOCK_TYPE(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
