// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 3.2.1.6 by WSRD Tencent.
// Generated from `NewsInfo.jce'
// **********************************************************************

package BEC;

public final class NewsType implements java.io.Serializable
{
    private static NewsType[] __values = new NewsType[3];
    private int __value;
    private String __T = new String();

    public static final int _NT_NEWS = 1;
    public static final NewsType NT_NEWS = new NewsType(0,_NT_NEWS,"NT_NEWS");
    public static final int _NT_REPORT = 2;
    public static final NewsType NT_REPORT = new NewsType(1,_NT_REPORT,"NT_REPORT");
    public static final int _NT_ANNOUNCEMENT = 3;
    public static final NewsType NT_ANNOUNCEMENT = new NewsType(2,_NT_ANNOUNCEMENT,"NT_ANNOUNCEMENT");

    public static NewsType convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static NewsType convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private NewsType(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
